
version: "3.4"
networks:
  proxylampy:
    external: true
  net:
    driver: overlay
    attachable: true
services:
  frontexec:
    image: koromerzhin/nodejs:1.1.3-quasar
    volumes:
      - ${PWD}/front:/app
    command: sh -c "npm install"
    deploy:
      restart_policy:
        condition: none
      labels:
        - "traefik.enable=false"
  backexec:
    image: koromerzhin/nodejs:15.1.0
    volumes:
      - ${PWD}/back:/app
    command: sh -c "npm install"
    deploy:
      restart_policy:
        condition: none
      labels:
        - "traefik.enable=false"
  build:
    image: nginx:alpine
    volumes:
      - ${PWD}/prod:/usr/share/nginx/html
    networks:
      - proxylampy
      - net
    depends_on:
      - back
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.build-repocheck.rule=HostRegexp(`repocheck.traefik.me`, `repocheck.{ip:.*}.traefik.me`) && PathPrefix(`/build`)"
        - "traefik.http.routers.build-repocheck-tls.tls.domains[0].main=repocheck.traefik.me"
        - "traefik.http.routers.build-repocheck-tls.tls.domains[0].sans=repocheck-*.traefik.me"
        - "traefik.http.routers.build-repocheck.tls=true"
        - "traefik.http.services.build-repocheck.loadbalancer.server.port=80"
  front:
    image: koromerzhin/nodejs:1.1.3-quasar
    volumes:
      - ${PWD}/front:/app
    networks:
      - proxylampy
      - net
    depends_on:
      - back
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.front-repocheck.rule=HostRegexp(`repocheck.traefik.me`, `repocheck.{ip:.*}.traefik.me`)"
        - "traefik.http.routers.front-repocheck-tls.tls.domains[0].main=repocheck.traefik.me"
        - "traefik.http.routers.front-repocheck-tls.tls.domains[0].sans=repocheck-*.traefik.me"
        - "traefik.http.routers.front-repocheck.tls=true"
        - "traefik.http.services.front-repocheck.loadbalancer.server.port=80"
  back:
    image: koromerzhin/nodejs:15.1.0
    volumes:
      - ${PWD}/back:/app
    networks:
      - proxylampy
      - net
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.back-repocheck.rule=HostRegexp(`repocheck.traefik.me`, `repocheck.{ip:.*}.traefik.me`) && PathPrefix(`/back`)"
        - "traefik.http.routers.back-repocheck-tls.tls.domains[0].main=repocheck.traefik.me"
        - "traefik.http.routers.back-repocheck-tls.tls.domains[0].sans=repocheck-*.traefik.me"
        - "traefik.http.routers.back-repocheck.tls=true"
        - "traefik.http.services.back-repocheck.loadbalancer.server.port=3000"