
version: "3.4"
networks:
  net:
    driver: overlay
    attachable: true
services:
  build:
    image: nginx:1.21.6-alpine
    volumes:
      - ${PWD}/prod:/usr/share/nginx/html
    networks:
      - net
    depends_on:
      - back
  front:
    image: node:15.14.0
    working_dir: /app
    command: >
      sh -c "npm install -g @quasar/cli@1.2.2 && npm install && npm run start"
    volumes:
      - ${PWD}/front:/app
    networks:
      - net
    depends_on:
      - back
  back:
    image: node:15.14.0
    working_dir: /app
    command: >
      sh -c "npm install && npm run start"
    volumes:
      - ${PWD}/back:/app
    networks:
      - net