
version: "3.4"
networks:
  proxylampy:
    external: true
services:
  build:
    networks:
      - proxylampy
      - net
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.build-repocheck.rule=Host(`repocheck.traefik.me`) && PathPrefix(`/build`)"
        - "traefik.http.routers.build-repocheck-tls.tls.domains[0].main=repocheck.traefik.me"
        - "traefik.http.routers.build-repocheck.tls=true"
        - "traefik.http.services.build-repocheck.loadbalancer.server.port=80"
  front:
    networks:
      - proxylampy
      - net
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.front-repocheck.rule=Host(`repocheck.traefik.me`)"
        - "traefik.http.routers.front-repocheck-tls.tls.domains[0].main=repocheck.traefik.me"
        - "traefik.http.routers.front-repocheck.tls=true"
        - "traefik.http.services.front-repocheck.loadbalancer.server.port=80"
  back:
    networks:
      - proxylampy
      - net
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.back-repocheck.rule=Host(`repocheck.traefik.me`) && PathPrefix(`/back`)"
        - "traefik.http.routers.back-repocheck-tls.tls.domains[0].main=repocheck.traefik.me"
        - "traefik.http.routers.back-repocheck.tls=true"
        - "traefik.http.services.back-repocheck.loadbalancer.server.port=3000"