
version: "3.4"
networks:
  proxynetwork:
    external: true
services:
  front:
    image: koromerzhin/nodejs:1.1.3-quasar
    volumes:
      - ${PWD}/front:/app
    networks:
      - proxynetwork
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.repocheck.rule=Host(`repocheck.traefik.me`)"
        - "traefik.http.routers.repocheck-tls.tls.domains[0].main=repocheck.traefik.me"
        - "traefik.http.routers.repocheck-tls.tls.domains[0].sans=repocheck-*.traefik.me"
        - "traefik.http.services.repocheck.loadbalancer.server.port=4200"