
version: "3.4"
networks:
  proxynetwork:
    external: true
  net:
    driver: overlay
    attachable: true
services:
  frontexec:
    image: koromerzhin/nodejs:1.1.3-quasar
    volumes:
      - ${PWD}/front:/app
    command: sh -c "npm install"
    deploy:
      labels:
        - "traefik.enable=false"
  backexec:
    image: koromerzhin/nodejs:15.1.0-express
    volumes:
      - ${PWD}/back:/app
    command: sh -c "npm install"
    deploy:
      labels:
        - "traefik.enable=false"
  front:
    image: koromerzhin/nodejs:1.1.3-quasar
    volumes:
      - ${PWD}/front:/app
    networks:
      - proxynetwork
      - net
    depends_on:
      - back
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.front-repocheck.rule=Host(`repocheck.traefik.me`)"
        - "traefik.http.routers.front-repocheck-tls.tls.domains[0].main=repocheck.traefik.me"
        - "traefik.http.routers.front-repocheck-tls.tls.domains[0].sans=repocheck.{ip:.*}.traefik.me"
        - "traefik.http.services.front-repocheck.loadbalancer.server.port=80"
  back:
    image: koromerzhin/nodejs:15.1.0-express
    volumes:
      - ${PWD}/back:/app
    networks:
      - proxynetwork
      - net
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.back-repocheck.rule=Host(`back-repocheck.traefik.me`)"
        - "traefik.http.routers.back-repocheck-tls.tls.domains[0].main=back-repocheck.traefik.me"
        - "traefik.http.routers.back-repocheck-tls.tls.domains[0].sans=back-repocheck.{ip:.*}.traefik.me"
        - "traefik.http.services.back-repocheck.loadbalancer.server.port=3000"